### ISSUE TITLE
Does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by MarcusLlewellyn** [daleglass/athena-builder#3]
This script fails on Ubuntu 16.04 when it attempts to find the `libdouble-conversion1` dependency, because this package does not exist on that version. There is a package called `libdouble-conversion1v5` that might be an appropriate substitute.

**Comment by daleglass** [comment]
In general, I think I'm not going to officially support 16.04 at this time, going too far back creates problems with things like cmake, and 18.04 is out and a lot more convenient.

I might revisit it at a later time, though.
